# Use official Python base image
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /app

# Copy current directory files to /app
COPY . /app

# Command to run app.py
CMD ["python", "app.py"]
